### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by baggepinnen** [baggepinnen/BasisFunctionExpansions.jl#2]
- [x] Initialization by clustering
- [x] Support also full covariance matrix using the clustering initialization
- [ ] Additional basis functions
- [ ] Parameter covariance
- [ ] Output covariance

**Comment by baggepinnen** [comment]
See Surrogates.jl
